use master

create database CoiffeurAppointmentSystem

use CoiffeurAppointmentSystem

CREATE SCHEMA cas;

create table cas.gender(
	gender_id int identity(1,1) primary key,
	gender varchar(20) not null)

create table cas.role(
	role_id int identity(1,1) primary key,
	role varchar(20) not null)

create table cas.city(
	city_id int identity(1,1) primary key,
	city nvarchar(20) not null)

create table cas.district(
	district_id int identity(1,1) primary key,
	city_id int foreign key references cas.city(city_id),
	district nvarchar(20) not null)

CREATE TABLE cas.person(
	user_id int IDENTITY(1,1) PRIMARY KEY,
	first_name nvarchar(50) NOT NULL,
	last_name nvarchar(50) NOT NULL,
	email varchar(70) not null,
	password varchar(50) NOT NULL,
	gender_id int FOREIGN KEY REFERENCES cas.gender(gender_id),
	city_id int FOREIGN KEY REFERENCES cas.city(city_id),
	district_id int FOREIGN KEY REFERENCES cas.district(district_id),
	create_date DATE not null DEFAULT(GETDATE()),
	birth_day date not null,
	img image,
	role_id int FOREIGN KEY REFERENCES cas.role(role_id)
	)

create table cas.workplace(
	wp_id int identity(1,1) primary key,
	wp_name nvarchar(50) not null,
	tel_no int not null,
	email varchar(70),
	about nvarchar(320),
	admin_id int foreign key references cas.person(user_id),
	city_id int FOREIGN KEY REFERENCES cas.city(city_id),
	district_id int FOREIGN KEY REFERENCES cas.district(district_id),
	address nvarchar(320) not null,
	zipcode int)

create table cas.employee(
	emp_id int identity(1,1) primary key,
	wp_id int foreign key references cas.workplace(wp_id),
	staff_id int foreign key references cas.person(user_id),
	description nvarchar(320))

create table cas.service(
	service_id int identity(1,1) primary key,
	service_name nvarchar(50) not null,
	)

create table cas.work(
	work_id int identity(1,1) primary key,
	staff_id int foreign key references cas.person(user_id),
	service_id int foreign key references cas.service(service_id),
	wp_id int foreign key references cas.workplace(wp_id),
	price int not null,
	description nvarchar(320),
	estimate_time int,)

create table cas.comment(
	comment_id int identity(1,1) primary key,
	comment nvarchar(320) not null,
	wp_id int foreign key references cas.workplace(wp_id),
	user_id int foreign key references cas.person(user_id))

create table cas.appointment(
	appointment_id int identity(1,1) primary key,
	appointment_date DATE not null DEFAULT(GETDATE()),
	user_id int foreign key references cas.person(user_id),
	wp_id int foreign key references cas.workplace(wp_id),
	staff_id int foreign key references cas.person(user_id),
	work_id int foreign key references cas.work(work_id))

INSERT INTO cas.gender VALUES
('Male'),
('Female')

INSERT INTO cas.role VALUES
('Admin'),
('User'),
('Staff')

INSERT INTO cas.city VALUES
('Adana'),
('Adýyaman'),
('Afyonkarahisar'),
('Aðrý'),
('Amasya'),
('Ankara'),
('Antalya'),
('Artvin'),
('Aydýn'),
('Balýkesir'),
('Bilecik'),
('Bingöl'),
('Bitlis'),
('Bolu'),
('Burdur'),
('Bursa'),
('Çanakkale'),
('Çankýrý'),
('Çorum'),
('Denizli'),
('Diyarbakýr'),
('Edirne'),
('Elazýð'),
('Erzincan'),
('Erzurum'),
('Eskiþehir'),
('Gaziantep'),
('Giresun'),
('Gümüþhane'),
('Hakkâri'),
('Hatay'),
('Isparta'),
('Mersin'),
('Ýstanbul'),
('Ýzmir'),
('Kars'),
('Kastamonu'),
('Kayseri'),
('Kýrklareli'),
('Kýrþehir'),
('Kocaeli'),
('Konya'),
('Kütahya'),
('Malatya'),
('Manisa'),
('Kahramanmaraþ'),
('Mardin'),
('Muðla'),
('Muþ'),
('Nevþehir'),
('Niðde'),
('Ordu'),
('Rize'),
('Sakarya'),
('Samsun'),
('Siirt'),
('Sinop'),
('Sivas'),
('Tekirdað'),
('Tokat'),
('Trabzon'),
('Tunceli'),
('Þanlýurfa'),
('Uþak'),
('Van'),
('Yozgat'),
('Zonguldak'),
('Aksaray'),
('Bayburt'),
('Karaman'),
('Kýrýkkale'),
('Batman'),
('Þýrnak'),
('Bartýn'),
('Ardahan'),
('Iðdýr'),
('Yalova'),
('Karabük'),
('Kilis'),
('Osmaniye'),
('Düzce')

insert into cas.district values
(1, 'Aladað'),
(1, 'Ceyhan'),
(1, 'Çukurova'),
(1, 'Feke'),
(1, 'Ýmamoðlu'),
(1, 'Karaisalý'),
(1, 'Karataþ'),
(1, 'Kozan'),
(1, 'Pozantý'),
(1, 'Saimbeyli'),
(1, 'Sarýçam'),
(1, 'Seyhan'),
(1, 'Tufanbeyli'),
(1, 'Yumurtalýk'),
(1, 'Yüreðir'),
(2, 'Merkez'),
(2, 'Besni'),
(2, 'Çelikhan'),
(2, 'Gerger'),
(2, 'Gölbaþý'),
(2, 'Kâhta'),
(2, 'Samsat'),
(2, 'Sincik'),
(2, 'Tut'),
(3, 'Merkez'),
(3, 'Baþmakçý'),
(3, 'Bayat'),
(3, 'Bolvadin'),
(3, 'Çay'),
(3, 'Çobanlar'),
(3, 'Dazkýrý'),
(3, 'Dinar'),
(3, 'Emirdað'),
(3, 'Evciler'),
(3, 'Hocalar'),
(3, 'Ýhsaniye'),
(3, 'Ýscehisar'),
(3, 'Kýzýlören'),
(3, 'Sandýklý'),
(3, 'Sinanpaþa'),
(3, 'Sultandaðý'),
(3, 'Þuhut'),
(4, 'Merkez'),
(4, 'Diyadin'),
(4, 'Doðubayazýt'),
(4, 'Eleþkirt'),
(4, 'Hamur'),
(4, 'Patnos'),
(4, 'Taþlýçay'),
(4, 'Tutak'),
(5, 'Merkez'),
(5, 'Göynücek'),
(5, 'Gümüþhacýköy'),
(5, 'Hamamözü'),
(5, 'Merzifon'),
(5, 'Suluova'),
(5, 'Taþova'),
(6, 'Akyurt'),
(6, 'Altýndað'),
(6, 'Ayaþ'),
(6, 'Balâ'),
(6, 'Beypazarý'),
(6, 'Çamlýdere'),
(6, 'Çankaya'),
(6, 'Çubuk'),
(6, 'Elmadað'),
(6, 'Etimesgut'),
(6, 'Evren'),
(6, 'Gölbaþý'),
(6, 'Güdül'),
(6, 'Haymana'),
(6, 'Kalecik'),
(6, 'Kahramankazan'),
(6, 'Keçiören'),
(6, 'Kýzýlcahamam'),
(6, 'Mamak'),
(6, 'Nallýhan'),
(6, 'Polatlý'),
(6, 'Pursaklar'),
(6, 'Sincan'),
(6, 'Þereflikoçhisar'),
(6, 'Yenimahalle'),
(7, 'Akseki'),
(7, 'Aksu'),
(7, 'Alanya'),
(7, 'Döþemealtý'),
(7, 'Elmalý'),
(7, 'Finike'),
(7, 'Gazipaþa'),
(7, 'Gündoðmuþ'),
(7, 'Ýbradý'),
(7, 'Demre'),
(7, 'Kaþ'),
(7, 'Kemer'),
(7, 'Kepez'),
(7, 'Konyaaltý'),
(7, 'Korkuteli'),
(7, 'Kumluca'),
(7, 'Manavgat'),
(7, 'Muratpaþa'),
(7, 'Serik'),
(8, 'Ardanuç'),
(8, 'Arhavi'),
(8, 'Merkez'),
(8, 'Borçka'),
(8, 'Hopa'),
(8, 'Kemalpaþa'),
(8, 'Murgul'),
(8, 'Þavþat'),
(8, 'Yusufeli'),
(9, 'Bozdoðan'),
(9, 'Buharkent'),
(9, 'Çine'),
(9, 'Didim'),
(9, 'Efeler'),
(9, 'Germencik'),
(9, 'Ýncirliova'),
(9, 'Karacasu'),
(9, 'Karpuzlu'),
(9, 'Koçarlý'),
(9, 'Köþk'),
(9, 'Kuþadasý'),
(9, 'Kuyucak'),
(9, 'Nazilli'),
(9, 'Söke'),
(9, 'Sultanhisar'),
(9, 'Yenipazar'),
(10, 'Altýeylül'),
(10, 'Ayvalýk'),
(10, 'Balya'),
(10, 'Bandýrma'),
(10, 'Bigadiç'),
(10, 'Burhaniye'),
(10, 'Dursunbey'),
(10, 'Edremit'),
(10, 'Erdek'),
(10, 'Gömeç'),
(10, 'Gönen'),
(10, 'Havran'),
(10, 'Ývrindi'),
(10, 'Karesi'),
(10, 'Kepsut'),
(10, 'Manyas'),
(10, 'Marmara'),
(10, 'Savaþtepe'),
(10, 'Sýndýrgý'),
(10, 'Susurluk'),
(11, 'Merkez'),
(11, 'Bozüyük'),
(11, 'Gölpazarý'),
(11, 'Ýnhisar'),
(11, 'Osmaneli'),
(11, 'Pazaryeri'),
(11, 'Söðüt'),
(11, 'Yenipazar'),
(12, 'Adaklý'),
(12, 'Merkez'),
(12, 'Genç'),
(12, 'Karlýova'),
(12, 'Kiðý'),
(12, 'Solhan'),
(12, 'Yayladere'),
(12, 'Yedisu'),
(13, 'Adilcevaz'),
(13, 'Ahlat'),
(13, 'Merkez'),
(13, 'Güroymak'),
(13, 'Hizan'),
(13, 'Mutki'),
(13, 'Tatvan'),
(14, 'Merkez'),
(14, 'Dörtdivan'),
(14, 'Gerede'),
(14, 'Göynük'),
(14, 'Kýbrýscýk'),
(14, 'Mengen'),
(14, 'Mudurnu'),
(14, 'Seben'),
(14, 'Yeniçaða'),
(15, 'Aðlasun'),
(15, 'Altýnyayla'),
(15, 'Bucak'),
(15, 'Merkez'),
(15, 'Çavdýr'),
(15, 'Çeltikçi'),
(15, 'Gölhisar'),
(15, 'Karamanlý'),
(15, 'Kemer'),
(15, 'Tefenni'),
(15, 'Yeþilova'),
(16, 'Büyükorhan'),
(16, 'Gemlik'),
(16, 'Gürsu'),
(16, 'Harmancýk'),
(16, 'Ýnegöl'),
(16, 'Ýznik'),
(16, 'Karacabey'),
(16, 'Keles'),
(16, 'Kestel'),
(16, 'Mudanya'),
(16, 'Mustafakemalpaþa'),
(16, 'Nilüfer'),
(16, 'Orhaneli'),
(16, 'Orhangazi'),
(16, 'Osmangazi'),
(16, 'Yeniþehir'),
(16, 'Yýldýrým'),
(17, 'Ayvacýk'),
(17, 'Bayramiç'),
(17, 'Biga'),
(17, 'Bozcaada'),
(17, 'Çan'),
(17, 'Merkez'),
(17, 'Eceabat'),
(17, 'Ezine'),
(17, 'Gelibolu'),
(17, 'Gökçeada'),
(17, 'Lapseki'),
(17, 'Yenice'),
(18, 'Atkaracalar'),
(18, 'Bayramören'),
(18, 'Merkez'),
(18, 'Çerkeþ'),
(18, 'Eldivan'),
(18, 'Ilgaz'),
(18, 'Kýzýlýrmak'),
(18, 'Korgun'),
(18, 'Kurþunlu'),
(18, 'Orta'),
(18, 'Þabanözü'),
(18, 'Yapraklý'),
(19, 'Alaca'),
(19, 'Bayat'),
(19, 'Boðazkale'),
(19, 'Merkez'),
(19, 'Dodurga'),
(19, 'Ýskilip'),
(19, 'Kargý'),
(19, 'Laçin'),
(19, 'Mecitözü'),
(19, 'Oðuzlar'),
(19, 'Ortaköy'),
(19, 'Osmancýk'),
(19, 'Sungurlu'),
(19, 'Uðurludað'),
(20, 'Acýpayam'),
(20, 'Babadað'),
(20, 'Baklan'),
(20, 'Bekilli'),
(20, 'Beyaðaç'),
(20, 'Bozkurt'),
(20, 'Buldan'),
(20, 'Çal'),
(20, 'Çameli'),
(20, 'Çardak'),
(20, 'Çivril'),
(20, 'Güney'),
(20, 'Honaz'),
(20, 'Kale'),
(20, 'Merkezefendi'),
(20, 'Pamukkale'),
(20, 'Sarayköy'),
(20, 'Serinhisar'),
(20, 'Tavas'),
(21, 'Baðlar'),
(21, 'Bismil'),
(21, 'Çermik'),
(21, 'Çýnar'),
(21, 'Çüngüþ'),
(21, 'Dicle'),
(21, 'Eðil'),
(21, 'Ergani'),
(21, 'Hani'),
(21, 'Hazro'),
(21, 'Kayapýnar'),
(21, 'Kocaköy'),
(21, 'Kulp'),
(21, 'Lice'),
(21, 'Silvan'),
(21, 'Sur'),
(21, 'Yeniþehir'),
(22, 'Merkez'),
(22, 'Enez'),
(22, 'Havsa'),
(22, 'Ýpsala'),
(22, 'Keþan'),
(22, 'Lalapaþa'),
(22, 'Meriç'),
(22, 'Süloðlu'),
(22, 'Uzunköprü'),
(23, 'Aðýn'),
(23, 'Alacakaya'),
(23, 'Arýcak'),
(23, 'Baskil'),
(23, 'Merkez'),
(23, 'Karakoçan'),
(23, 'Keban'),
(23, 'Kovancýlar'),
(23, 'Maden'),
(23, 'Palu'),
(23, 'Sivrice'),
(24, 'Çayýrlý'),
(24, 'Merkez'),
(24, 'Ýliç'),
(24, 'Kemah'),
(24, 'Kemaliye'),
(24, 'Otlukbeli'),
(24, 'Refahiye'),
(24, 'Tercan'),
(24, 'Üzümlü'),
(25, 'Aþkale'),
(25, 'Aziziye'),
(25, 'Çat'),
(25, 'Hýnýs'),
(25, 'Horasan'),
(25, 'Ýspir'),
(25, 'Karaçoban'),
(25, 'Karayazý'),
(25, 'Köprüköy'),
(25, 'Narman'),
(25, 'Oltu'),
(25, 'Olur'),
(25, 'Palandöken'),
(25, 'Pasinler'),
(25, 'Pazaryolu'),
(25, 'Þenkaya'),
(25, 'Tekman'),
(25, 'Tortum'),
(25, 'Uzundere'),
(25, 'Yakutiye'),
(26, 'Alpu'),
(26, 'Beylikova'),
(26, 'Çifteler'),
(26, 'Günyüzü'),
(26, 'Han'),
(26, 'Ýnönü'),
(26, 'Mahmudiye'),
(26, 'Mihalgazi'),
(26, 'Mihalýççýk'),
(26, 'Odunpazarý'),
(26, 'Sarýcakaya'),
(26, 'Seyitgazi'),
(26, 'Sivrihisar'),
(26, 'Tepebaþý'),
(27, 'Araban'),
(27, 'Ýslahiye'),
(27, 'Karkamýþ'),
(27, 'Nizip'),
(27, 'Nurdaðý'),
(27, 'Oðuzeli'),
(27, 'Þahinbey'),
(27, 'Þehitkamil'),
(27, 'Yavuzeli'),
(28, 'Alucra'),
(28, 'Bulancak'),
(28, 'Çamoluk'),
(28, 'Çanakçý'),
(28, 'Dereli'),
(28, 'Doðankent'),
(28, 'Espiye'),
(28, 'Eynesil'),
(28, 'Merkez'),
(28, 'Görele'),
(28, 'Güce'),
(28, 'Keþap'),
(28, 'Piraziz'),
(28, 'Þebinkarahisar'),
(28, 'Tirebolu'),
(28, 'Yaðlýdere'),
(29, 'Merkez'),
(29, 'Kelkit'),
(29, 'Köse'),
(29, 'Kürtün'),
(29, 'Þiran'),
(29, 'Torul'),
(30, 'Çukurca'),
(30, 'Merkez'),
(30, 'Þemdinli'),
(30, 'Yüksekova'),
(30, 'Derecik'),
(31, 'Altýnözü'),
(31, 'Antakya'),
(31, 'Arsuz'),
(31, 'Belen'),
(31, 'Defne'),
(31, 'Dörtyol'),
(31, 'Erzin'),
(31, 'Hassa'),
(31, 'Ýskenderun'),
(31, 'Kýrýkhan'),
(31, 'Kumlu'),
(31, 'Payas'),
(31, 'Reyhanlý'),
(31, 'Samandað'),
(31, 'Yayladaðý'),
(32, 'Aksu'),
(32, 'Atabey'),
(32, 'Eðirdir'),
(32, 'Gelendost'),
(32, 'Gönen'),
(32, 'Merkez'),
(32, 'Keçiborlu'),
(32, 'Senirkent'),
(32, 'Sütçüler'),
(32, 'Þarkikaraaðaç'),
(32, 'Uluborlu'),
(32, 'Yalvaç'),
(32, 'Yeniþarbademli'),
(33, 'Akdeniz'),
(33, 'Anamur'),
(33, 'Aydýncýk'),
(33, 'Bozyazý'),
(33, 'Çamlýyayla'),
(33, 'Erdemli'),
(33, 'Gülnar'),
(33, 'Mezitli'),
(33, 'Mut'),
(33, 'Silifke'),
(33, 'Tarsus'),
(33, 'Toroslar'),
(33, 'Yeniþehir'),
(34, 'Adalar'),
(34, 'Arnavutköy'),
(34, 'Ataþehir'),
(34, 'Avcýlar'),
(34, 'Baðcýlar'),
(34, 'Bahçelievler'),
(34, 'Bakýrköy'),
(34, 'Baþakþehir'),
(34, 'Bayrampaþa'),
(34, 'Beþiktaþ'),
(34, 'Beykoz'),
(34, 'Beylikdüzü'),
(34, 'Beyoðlu'),
(34, 'Büyükçekmece'),
(34, 'Çatalca'),
(34, 'Çekmeköy'),
(34, 'Esenler'),
(34, 'Esenyurt'),
(34, 'Eyüpsultan'),
(34, 'Fatih'),
(34, 'Gaziosmanpaþa'),
(34, 'Güngören'),
(34, 'Kadýköy'),
(34, 'Kâðýthane'),
(34, 'Kartal'),
(34, 'Küçükçekmece'),
(34, 'Maltepe'),
(34, 'Pendik'),
(34, 'Sancaktepe'),
(34, 'Sarýyer'),
(34, 'Silivri'),
(34, 'Sultanbeyli'),
(34, 'Sultangazi'),
(34, 'Þile'),
(34, 'Þiþli'),
(34, 'Tuzla'),
(34, 'Ümraniye'),
(34, 'Üsküdar'),
(34, 'Zeytinburnu'),
(35, 'Aliaða'),
(35, 'Balçova'),
(35, 'Bayýndýr'),
(35, 'Bayraklý'),
(35, 'Bergama'),
(35, 'Beydað'),
(35, 'Bornova'),
(35, 'Buca'),
(35, 'Çeþme'),
(35, 'Çiðli'),
(35, 'Dikili'),
(35, 'Foça'),
(35, 'Gaziemir'),
(35, 'Güzelbahçe'),
(35, 'Karabaðlar'),
(35, 'Karaburun'),
(35, 'Karþýyaka'),
(35, 'Kemalpaþa'),
(35, 'Kýnýk'),
(35, 'Kiraz'),
(35, 'Konak'),
(35, 'Menderes'),
(35, 'Menemen'),
(35, 'Narlýdere'),
(35, 'Ödemiþ'),
(35, 'Seferihisar'),
(35, 'Selçuk'),
(35, 'Tire'),
(35, 'Torbalý'),
(35, 'Urla'),
(36, 'Akyaka'),
(36, 'Arpaçay'),
(36, 'Digor'),
(36, 'Kaðýzman'),
(36, 'Merkez'),
(36, 'Sarýkamýþ'),
(36, 'Selim'),
(36, 'Susuz'),
(37, 'Abana'),
(37, 'Aðlý'),
(37, 'Araç'),
(37, 'Azdavay'),
(37, 'Bozkurt'),
(37, 'Cide'),
(37, 'Çatalzeytin'),
(37, 'Daday'),
(37, 'Devrekani'),
(37, 'Doðanyurt'),
(37, 'Hanönü'),
(37, 'Ýhsangazi'),
(37, 'Ýnebolu'),
(37, 'Merkez'),
(37, 'Küre'),
(37, 'Pýnarbaþý'),
(37, 'Seydiler'),
(37, 'Þenpazar'),
(37, 'Taþköprü'),
(37, 'Tosya'),
(38, 'Akkýþla'),
(38, 'Bünyan'),
(38, 'Develi'),
(38, 'Felahiye'),
(38, 'Hacýlar'),
(38, 'Ýncesu'),
(38, 'Kocasinan'),
(38, 'Melikgazi'),
(38, 'Özvatan'),
(38, 'Pýnarbaþý'),
(38, 'Sarýoðlan'),
(38, 'Sarýz'),
(38, 'Talas'),
(38, 'Tomarza'),
(38, 'Yahyalý'),
(38, 'Yeþilhisar'),
(39, 'Babaeski'),
(39, 'Demirköy'),
(39, 'Merkez'),
(39, 'Kofçaz'),
(39, 'Lüleburgaz'),
(39, 'Pehlivanköy'),
(39, 'Pýnarhisar'),
(39, 'Vize'),
(40, 'Akçakent'),
(40, 'Akpýnar'),
(40, 'Boztepe'),
(40, 'Çiçekdaðý'),
(40, 'Kaman'),
(40, 'Kýrþehir'),
(40, 'Mucur'),
(41, 'Baþiskele'),
(41, 'Çayýrova'),
(41, 'Darýca'),
(41, 'Derince'),
(41, 'Dilovasý'),
(41, 'Gebze'),
(41, 'Gölcük'),
(41, 'Ýzmit'),
(41, 'Kandýra'),
(41, 'Karamürsel'),
(41, 'Kartepe'),
(41, 'Körfez'),
(42, 'Ahýrlý'),
(42, 'Akören'),
(42, 'Akþehir'),
(42, 'Altýnekin'),
(42, 'Beyþehir'),
(42, 'Bozkýr'),
(42, 'Cihanbeyli'),
(42, 'Çeltik'),
(42, 'Çumra'),
(42, 'Derbent'),
(42, 'Derebucak'),
(42, 'Doðanhisar'),
(42, 'Emirgazi'),
(42, 'Ereðli'),
(42, 'Güneysýnýr'),
(42, 'Hadim'),
(42, 'Halkapýnar'),
(42, 'Hüyük'),
(42, 'Ilgýn'),
(42, 'Kadýnhaný'),
(42, 'Karapýnar'),
(42, 'Karatay'),
(42, 'Kulu'),
(42, 'Meram'),
(42, 'Sarayönü'),
(42, 'Selçuklu'),
(42, 'Seydiþehir'),
(42, 'Taþkent'),
(42, 'Tuzlukçu'),
(42, 'Yalýhüyük'),
(42, 'Yunak'),
(43, 'Altýntaþ'),
(43, 'Aslanapa'),
(43, 'Çavdarhisar'),
(43, 'Domaniç'),
(43, 'Dumlupýnar'),
(43, 'Emet'),
(43, 'Gediz'),
(43, 'Hisarcýk'),
(43, 'Kütahya'),
(43, 'Pazarlar'),
(43, 'Þaphane'),
(43, 'Simav'),
(43, 'Tavþanlý'),
(44, 'Akçadað'),
(44, 'Arapgir'),
(44, 'Arguvan'),
(44, 'Battalgazi'),
(44, 'Darende'),
(44, 'Doðanþehir'),
(44, 'Doðanyol'),
(44, 'Hekimhan'),
(44, 'Kale'),
(44, 'Kuluncak'),
(44, 'Pütürge'),
(44, 'Yazýhan'),
(44, 'Yeþilyurt'),
(45, 'Ahmetli'),
(45, 'Akhisar'),
(45, 'Alaþehir'),
(45, 'Demirci'),
(45, 'Gölmarmara'),
(45, 'Gördes'),
(45, 'Kýrkaðaç'),
(45, 'Köprübaþý'),
(45, 'Kula'),
(45, 'Salihli'),
(45, 'Sarýgöl'),
(45, 'Saruhanlý'),
(45, 'Selendi'),
(45, 'Soma'),
(45, 'Þehzadeler'),
(45, 'Turgutlu'),
(45, 'Yunusemre'),
(46, 'Afþin'),
(46, 'Andýrýn'),
(46, 'Çaðlayancerit'),
(46, 'Dulkadiroðlu'),
(46, 'Ekinözü'),
(46, 'Elbistan'),
(46, 'Göksun'),
(46, 'Nurhak'),
(46, 'Onikiþubat'),
(46, 'Pazarcýk'),
(46, 'Türkoðlu'),
(47, 'Artuklu'),
(47, 'Dargeçit'),
(47, 'Derik'),
(47, 'Kýzýltepe'),
(47, 'Mazýdaðý'),
(47, 'Midyat'),
(47, 'Nusaybin'),
(47, 'Ömerli'),
(47, 'Savur'),
(47, 'Yeþilli'),
(48, 'Bodrum'),
(48, 'Dalaman'),
(48, 'Datça'),
(48, 'Fethiye'),
(48, 'Kavaklýdere'),
(48, 'Köyceðiz'),
(48, 'Marmaris'),
(48, 'Menteþe'),
(48, 'Milas'),
(48, 'Ortaca'),
(48, 'Seydikemer'),
(48, 'Ula'),
(48, 'Yataðan'),
(49, 'Bulanýk'),
(49, 'Hasköy'),
(49, 'Korkut'),
(49, 'Malazgirt'),
(49, 'Merkez'),
(49, 'Varto'),
(50, 'Acýgöl'),
(50, 'Avanos'),
(50, 'Derinkuyu'),
(50, 'Gülþehir'),
(50, 'Hacýbektaþ'),
(50, 'Kozaklý'),
(50, 'Merkez'),
(50, 'Ürgüp'),
(51, 'Altunhisar'),
(51, 'Bor'),
(51, 'Çamardý'),
(51, 'Çiftlik'),
(51, 'Merkez'),
(51, 'Ulukýþla'),
(52, 'Akkuþ'),
(52, 'Altýnordu'),
(52, 'Aybastý'),
(52, 'Çamaþ'),
(52, 'Çatalpýnar'),
(52, 'Çaybaþý'),
(52, 'Fatsa'),
(52, 'Gölköy'),
(52, 'Gülyalý'),
(52, 'Gürgentepe'),
(52, 'Ýkizce'),
(52, 'Kabadüz'),
(52, 'Kabataþ'),
(52, 'Korgan'),
(52, 'Kumru'),
(52, 'Mesudiye'),
(52, 'Perþembe'),
(52, 'Ulubey'),
(52, 'Ünye'),
(53, 'Ardeþen'),
(53, 'Çamlýhemþin'),
(53, 'Çayeli'),
(53, 'Derepazarý'),
(53, 'Fýndýklý'),
(53, 'Güneysu'),
(53, 'Hemþin'),
(53, 'Ýkizdere'),
(53, 'Ýyidere'),
(53, 'Kalkandere'),
(53, 'Pazar'),
(53, 'Rize'),
(54, 'Adapazarý'),
(54, 'Akyazý'),
(54, 'Arifiye'),
(54, 'Erenler'),
(54, 'Ferizli'),
(54, 'Geyve'),
(54, 'Hendek'),
(54, 'Karapürçek'),
(54, 'Karasu'),
(54, 'Kaynarca'),
(54, 'Kocaali'),
(54, 'Pamukova'),
(54, 'Sapanca'),
(54, 'Serdivan'),
(54, 'Söðütlü'),
(54, 'Taraklý'),
(55, 'Alaçam'),
(55, 'Asarcýk'),
(55, 'Atakum'),
(55, 'Ayvacýk'),
(55, 'Bafra'),
(55, 'Canik'),
(55, 'Çarþamba'),
(55, 'Havza'),
(55, 'Ýlkadým'),
(55, 'Kavak'),
(55, 'Ladik'),
(55, 'Ondokuzmayýs'),
(55, 'Salýpazarý'),
(55, 'Tekkeköy'),
(55, 'Terme'),
(55, 'Vezirköprü'),
(55, 'Yakakent'),
(56, 'Merkez'),
(56, 'Tillo'),
(56, 'Baykan'),
(56, 'Eruh'),
(56, 'Kurtalan'),
(56, 'Pervari'),
(56, 'Þirvan'),
(57, 'Ayancýk'),
(57, 'Boyabat'),
(57, 'Dikmen'),
(57, 'Duraðan'),
(57, 'Erfelek'),
(57, 'Gerze'),
(57, 'Saraydüzü'),
(57, 'Merkez'),
(57, 'Türkeli'),
(58, 'Akýncýlar'),
(58, 'Altýnyayla'),
(58, 'Divriði'),
(58, 'Doðanþar'),
(58, 'Gemerek'),
(58, 'Gölova'),
(58, 'Hafik'),
(58, 'Ýmranlý'),
(58, 'Kangal'),
(58, 'Koyulhisar'),
(58, 'Sivas'),
(58, 'Suþehri'),
(58, 'Þarkýþla'),
(58, 'Ulaþ'),
(58, 'Yýldýzeli'),
(58, 'Zara'),
(58, 'Gürün'),
(59, 'Çerkezköy'),
(59, 'Çorlu'),
(59, 'Ergene'),
(59, 'Hayrabolu'),
(59, 'Kapaklý'),
(59, 'Malkara'),
(59, 'Marmaraereðlisi'),
(59, 'Muratlý'),
(59, 'Saray'),
(59, 'Süleymanpaþa'),
(59, 'Þarköy'),
(60, 'Almus'),
(60, 'Artova'),
(60, 'Baþçiftlik'),
(60, 'Erbaa'),
(60, 'Niksar'),
(60, 'Pazar'),
(60, 'Reþadiye'),
(60, 'Sulusaray'),
(60, 'Merkez'),
(60, 'Turhal'),
(60, 'Yeþilyurt'),
(60, 'Zile'),
(61, 'Akçaabat'),
(61, 'Araklý'),
(61, 'Arsin'),
(61, 'Beþikdüzü'),
(61, 'Çarþýbaþý'),
(61, 'Çaykara'),
(61, 'Dernekpazarý'),
(61, 'Düzköy'),
(61, 'Hayrat'),
(61, 'Köprübaþý'),
(61, 'Maçka'),
(61, 'Of'),
(61, 'Ortahisar'),
(61, 'Sürmene'),
(61, 'Þalpazarý'),
(61, 'Tonya'),
(61, 'Vakfýkebir'),
(61, 'Yomra'),
(62, 'Çemiþgezek'),
(62, 'Hozat'),
(62, 'Mazgirt'),
(62, 'Nazýmiye'),
(62, 'Ovacýk'),
(62, 'Pertek'),
(62, 'Pülümür'),
(62, 'Tunceli'),
(63, 'Akçakale'),
(63, 'Birecik'),
(63, 'Bozova'),
(63, 'Ceylanpýnar'),
(63, 'Eyyübiye'),
(63, 'Halfeti'),
(63, 'Haliliye'),
(63, 'Harran'),
(63, 'Hilvan'),
(63, 'Karaköprü'),
(63, 'Siverek'),
(63, 'Suruç'),
(63, 'Viranþehir'),
(64, 'Banaz'),
(64, 'Eþme'),
(64, 'Karahallý'),
(64, 'Sivaslý'),
(64, 'Ulubey'),
(64, 'Merkez'),
(65, 'Bahçesaray'),
(65, 'Baþkale'),
(65, 'Çaldýran'),
(65, 'Çatak'),
(65, 'Edremit'),
(65, 'Erciþ'),
(65, 'Gevaþ'),
(65, 'Gürpýnar'),
(65, 'Ýpekyolu'),
(65, 'Muradiye'),
(65, 'Özalp'),
(65, 'Saray'),
(65, 'Tuþba'),
(66, 'Akdaðmadeni'),
(66, 'Aydýncýk'),
(66, 'Boðazlýyan'),
(66, 'Çandýr'),
(66, 'Çayýralan'),
(66, 'Çekerek'),
(66, 'Kadýþehri'),
(66, 'Saraykent'),
(66, 'Sarýkaya'),
(66, 'Sorgun'),
(66, 'Þefaatli'),
(66, 'Yenifakýlý'),
(66, 'Yerköy'),
(66, 'Merkez'),
(67, 'Alaplý'),
(67, 'Çaycuma'),
(67, 'Devrek'),
(67, 'Gökçebey'),
(67, 'Kilimli'),
(67, 'Kozlu'),
(67, 'Karadeniz Ereðli'),
(67, 'Merkez'),
(68, 'Aðaçören'),
(68, 'Merkez'),
(68, 'Eskil'),
(68, 'Gülaðaç'),
(68, 'Güzelyurt'),
(68, 'Ortaköy'),
(68, 'Sarýyahþi'),
(68, 'Sultanhaný'),
(69, 'Aydýntepe'),
(69, 'Merkez'),
(69, 'Demirözü'),
(70, 'Ayrancý'),
(70, 'Baþyayla'),
(70, 'Ermenek'),
(70, 'Merkez'),
(70, 'Kazýmkarabekir'),
(70, 'Sarýveliler'),
(71, 'Bahþili'),
(71, 'Balýþeyh'),
(71, 'Çelebi'),
(71, 'Delice'),
(71, 'Karakeçili'),
(71, 'Keskin'),
(71, 'Merkez'),
(71, 'Sulakyurt'),
(71, 'Yahþihan'),
(72, 'Merkez'),
(72, 'Beþiri'),
(72, 'Gercüþ'),
(72, 'Hasankeyf'),
(72, 'Kozluk'),
(72, 'Sason'),
(73, 'Beytüþþebap'),
(73, 'Cizre'),
(73, 'Güçlükonak'),
(73, 'Ýdil'),
(73, 'Silopi'),
(73, 'Merkez'),
(73, 'Uludere'),
(74, 'Amasra'),
(74, 'Merkez'),
(74, 'Kurucaþile'),
(74, 'Ulus'),
(75, 'Merkez'),
(75, 'Çýldýr'),
(75, 'Damal'),
(75, 'Göle'),
(75, 'Hanak'),
(75, 'Posof'),
(76, 'Aralýk'),
(76, 'Merkez'),
(76, 'Karakoyunlu'),
(76, 'Tuzluca'),
(77, 'Altýnova'),
(77, 'Armutlu'),
(77, 'Çýnarcýk'),
(77, 'Çiftlikköy'),
(77, 'Termal'),
(77, 'Merkez'),
(78, 'Eflani'),
(78, 'Eskipazar'),
(78, 'Merkez'),
(78, 'Ovacýk'),
(78, 'Safranbolu'),
(78, 'Yenice'),
(79, 'Elbeyli'),
(79, 'Merkez'),
(79, 'Musabeyli'),
(79, 'Polateli'),
(80, 'Bahçe'),
(80, 'Düziçi'),
(80, 'Hasanbeyli'),
(80, 'Kadirli'),
(80, 'Merkez'),
(80, 'Sumbas'),
(80, 'Toprakkale'),
(81, 'Akçakoca'),
(81, 'Cumayeri'),
(81, 'Çilimli'),
(81, 'Merkez'),
(81, 'Gölyaka'),
(81, 'Gümüþova'),
(81, 'Kaynaþlý'),
(81, 'Yýðýlca')

insert into cas.service values
('Haircut'),('Beard Cut'),('Manicure'),('Pedicure')

select * from cas.service