//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coiffeur_Appointment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int appointment_id { get; set; }
        public System.DateTime appointment_date { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> wp_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<int> work_id { get; set; }
    
        public virtual person person { get; set; }
        public virtual person person1 { get; set; }
        public virtual work work { get; set; }
        public virtual workplace workplace { get; set; }
    }
}
