//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coiffeur_Appointment_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoiffeurAppointmentSystemEntities : DbContext
    {
        public CoiffeurAppointmentSystemEntities()
            : base("name=CoiffeurAppointmentSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointment { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<work> work { get; set; }
        public virtual DbSet<workplace> workplace { get; set; }
    }
}
