//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coiffeur_Appointment_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class workplace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public workplace()
        {
            this.appointment = new HashSet<appointment>();
            this.comment = new HashSet<comment>();
            this.employee = new HashSet<employee>();
            this.work = new HashSet<work>();
        }
    
        public int wp_id { get; set; }
        public string wp_name { get; set; }
        public int tel_no { get; set; }
        public string email { get; set; }
        public string about { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public string address { get; set; }
        public Nullable<int> zipcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointment { get; set; }
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee { get; set; }
        public virtual person person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<work> work { get; set; }
    }
}
